template = "https://github.com/giellalt/template-lang-und"
rev_id = 295
template_sha = "9e160f410d669a53f8b740a218fd6462f17d3234"

[replacements]
__GLOTTOLOG_ID__ = "para1311"
__REPO__ = "lang-grn"
__UND2C__ = "gn"
__UNDEFINED__ = "Guarani"
__UND__ = "grn"
