template = "https://github.com/giellalt/template-lang-und"
rev_id = 316
template_sha = "4ab8b281df40078b127cd15db6e63507b51b4424"

[replacements]
__GLOTTOLOG_ID__ = "para1311"
__REPO__ = "lang-grn"
__UND2C__ = "gn"
__UNDEFINED__ = "Guarani"
__UND__ = "grn"
